# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"imglmdb": "imglmdb.ipynb"}

modules = ["imglmdb.py"]

doc_url = "https://mlippeve.github.io/ifcimglib/"

git_url = "https://github.com/mlippeve/ifcimglib/tree/master/"

def custom_doc_links(name): return None
